### PR TITLE
Converted the project to build through Gradle.

### PR DESCRIPTION
**Pull request by mikesena**
(If you want it..)

### CODE REVIEW

**Comment by na-ka-na** [comment]
Hmm I have never used Gradle. You might make me want it if you tell me why I should use Gradle first. Also I'd need you to update the 'BUILDING' file to leave instructions on how to replace my current usage.

**Comment by mikesena** [comment]
Ah; not wanting to convince you.  I prefer Maven or Gradle as they tend to be more commonly used (at least, that is my experience) - more modern.  Ivy also annoys me ;)

I'll fix the BUILDING file now.

**Comment by mikesena** [comment]
Corrected it and also set the source compatibility.

**Comment by syshenyao** [comment]
I think this is a good suggestion. After all, Maven and gradle are more popular. Ant and ivy increase the learning cost

**Pull request closed without merging**
